### ISSUE TITLE
API needed

### ISSUE THREAD

**Issue by werdna521** [bearcatsdev/adab-renom#4]
Please **create** the following **APIs** for Adab's Admin page

1. **GET** - Retrieve All Users
2. **GET** - Retrieve All Courses
3. **GET** - Retrieve All Sessions
4. **POST** - Create New User
5. **POST** - Create New Course
6. **POST** - Create New Session
7. **PUT/PATCH** - Update Existing User Details
8. **PUT/PATCH** - Update Existing Course Details
9. **PUT/PATCH** - Update Existing Session Details

Those are the APIs that I could think of right now. If I eventually need another API, I will update this issue. Please create the APIs **ASAP** as the admin page is useless without it.

**Comment by werdna521** [comment]
Maybe @developerchan1 can help as he's currently not assigned to any task? @brianrahula @DevitaSetyaningrum @AngSanley

**Comment by brainwo** [comment]
Out for a while, will continue tommorow (hopefully)

**Comment by brainwo** [comment]
Could you help specify how and where the API should we make?

**Comment by angsanley** [comment]
I'm currently quite occupied with the frontend web app task. I'll try to help after I'm done with frontend.

**Comment by werdna521** [comment]
Alright, I think I'll assign @developerchan1 for now

**Comment by angsanley** [comment]
How's the progress with this issue?

**Comment by werdna521** [comment]
@developerchan1 should be working on it. He has even made a PR #5 which only lacks an authentication middleware

**Comment by developerchan1** [comment]
@werdna521 I have added a middleware for session called "express-session". But, I have a problem now. In every login for admin, the sessionID always generated. Can you help me? Because actually I am still not really know about session yet.
